namespace CSML.Generator;

internal static class CodeSnippets
{
    public const string VERSION = "dev-1";
    public const string COMPILER_NAME = "CSML Compiler";
    public const string GENERATED_CODE_ATTRIBUTE = $$"""[System.CodeDom.Compiler.GeneratedCode("{{COMPILER_NAME}}", "{{VERSION}}")]""";

    public const string GENERATED_CODE_COMMENT_HEADER = """
        // generated code
        """;

    public static string CreateBasicCode()
    {
        return $$"""
            // generated code
                                
            /*******************************************************************************
            * Generated by CSML Source Generator created by Dineinger                      *
            * Auther: https://github.com/Dineinger                                         *
            * Repo:https://github.com/Dineinger/CSMLib                                     *
            *******************************************************************************/
            
            using System;
            using System.CodeDom.Compiler;
            
            namespace CSML;
            
            {{GENERATED_CODE_ATTRIBUTE}}
            [AttributeUsage(AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
            public sealed class CSMLCodeAttribute<T> : Attribute
            {
                public CSMLCodeAttribute(string csmlCode)
                {
                    CsmlCode = csmlCode;
                }

                public string CsmlCode { get; }
            }
            
            {{GENERATED_CODE_ATTRIBUTE}}
            public interface ICSMLClass<T>
                where T : ICSMLClass<T>
            {
                static abstract T New();
            }
            
            {{GENERATED_CODE_ATTRIBUTE}}
            public class CSMLTranslator
            {
                public static T From<T>(string csml)
                    where T : ICSMLClass<T>
                {
                    var result = T.New();
            
                    return result;
                }
            }
            """;
    }
}
